# Generated by Django 2.2.5 on 2019-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190918_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='engaggr',
            field=models.FloatField(max_length='4'),
        ),
    ]
