# Generated by Django 2.2.5 on 2019-09-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190918_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='engaggr',
            field=models.FloatField(max_length='4', verbose_name='Engineering Aggregate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twelveth',
            field=models.FloatField(max_length='4', verbose_name='12th Percentage'),
        ),
    ]
