# Generated by Django 2.2.5 on 2019-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190918_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='engaggr',
            field=models.FloatField(default='Please Update', max_length='4', verbose_name='Engineering Aggregate (Percentile)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenth',
            field=models.FloatField(default=-1, max_length=100, verbose_name='10th Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twelveth',
            field=models.FloatField(default='-', max_length=100, verbose_name='12th Percentage'),
        ),
    ]
