# Generated by Django 2.2.5 on 2019-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190921_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tenth',
            field=models.FloatField(default=0, max_length=100, verbose_name='10th Percentage'),
        ),
    ]
