# Generated by Django 2.2.4 on 2019-09-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190922_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievances',
            name='user',
        ),
    ]
