# Generated by Django 2.2.4 on 2019-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190922_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievances',
            name='user_query',
            field=models.TextField(default='Q. ', max_length=200, verbose_name='Question:'),
        ),
    ]
