# Generated by Django 2.2.4 on 2019-09-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190922_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievances',
            name='is_answered',
            field=models.BooleanField(default=True, verbose_name='Is Answered?:'),
        ),
    ]
