# Generated by Django 2.2.5 on 2019-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='engg',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='ten',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='twelve',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
